server:
  port: ${PUERTO_APP:8082}

spring:
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@//oracle-xe:1521/XEPDB1}
    username: ${ORACLE_USR:SERVICIO_CUENTAS}
    password: ${ORACLE_PWD:secreto}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: servicio-cuentas-grp
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web.exposure.include: health,info
