server:
  port: ${PUERTO_APP:8082}

spring:
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@//oracle-xe:1521/XEPDB1}
    username: ${ORACLE_USR:SERVICIO_CUENTAS}
    password: ${ORACLE_PWD:secreto}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
