server:
  port: ${PUERTO_APP:8081}

spring:
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
    username: ${ORACLE_USR:SERVICIO_PERSONAS}
    password: ${ORACLE_PWD:secreto}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
