-- =============================================================
-- Script único: Oracle19c_microservicios_es_NUMERIC_SEQ.sql
-- Objetivo: Crear usuarios/esquemas, tablas y FK entre servicios
--           con IDs NUMERIC/NUMBER(19) y generación por SECUENCIAS
-- =============================================================

-- ====================
-- Servicio de Personas
-- ====================
CREATE USER SERVICIO_PERSONAS IDENTIFIED BY "secreto"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
      CREATE PROCEDURE TO SERVICIO_PERSONAS;

-- Tablas
CREATE TABLE SERVICIO_PERSONAS.PERSONA (
  ID NUMBER(19) PRIMARY KEY,
  NOMBRE VARCHAR2(120) NOT NULL,
  GENERO VARCHAR2(20),
  EDAD NUMBER(10),
  IDENTIFICACION VARCHAR2(50) NOT NULL,
  DIRECCION VARCHAR2(200),
  TELEFONO VARCHAR2(30),
  CONSTRAINT UQ_PERSONA_IDENTIFICACION UNIQUE (IDENTIFICACION)
);

CREATE TABLE SERVICIO_PERSONAS.CLIENTE (
  ID_CLIENTE NUMBER(19) PRIMARY KEY,
  ID_PERSONA NUMBER(19) NOT NULL,
  CONTRASENA_HASH VARCHAR2(200) NOT NULL,
  ESTADO NUMBER(1) DEFAULT 1 NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY (ID_PERSONA)
    REFERENCES SERVICIO_PERSONAS.PERSONA(ID),
  CONSTRAINT CK_CLIENTE_ESTADO CHECK (ESTADO IN (0,1))
);

CREATE INDEX SERVICIO_PERSONAS.IDX_CLIENTE_PERSONA
  ON SERVICIO_PERSONAS.CLIENTE(ID_PERSONA);

-- Secuencias
CREATE SEQUENCE SERVICIO_PERSONAS.SEQ_PERSONA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SERVICIO_PERSONAS.SEQ_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ====================
-- Servicio de Cuentas
-- ====================
CREATE USER SERVICIO_CUENTAS IDENTIFIED BY "secreto"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
      CREATE PROCEDURE TO SERVICIO_CUENTAS;

-- Permisos inter-esquema
GRANT REFERENCES ON SERVICIO_PERSONAS.CLIENTE TO SERVICIO_CUENTAS;
GRANT SELECT     ON SERVICIO_PERSONAS.CLIENTE TO SERVICIO_CUENTAS;

-- Tablas
CREATE TABLE SERVICIO_CUENTAS.CUENTA (
  ID NUMBER(19) PRIMARY KEY,
  NUMERO_CUENTA VARCHAR2(30) NOT NULL,
  TIPO VARCHAR2(20) NOT NULL,
  SALDO_INICIAL NUMBER(18,2) NOT NULL,
  ESTADO NUMBER(1) DEFAULT 1 NOT NULL,
  ID_CLIENTE NUMBER(19) NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_CUENTA_NUMERO UNIQUE (NUMERO_CUENTA),
  CONSTRAINT CK_CUENTA_TIPO CHECK (TIPO IN ('AHORROS','CORRIENTE')),
  CONSTRAINT CK_CUENTA_ESTADO CHECK (ESTADO IN (0,1))
);

CREATE TABLE SERVICIO_CUENTAS.MOVIMIENTO (
  ID NUMBER(19) PRIMARY KEY,
  FECHA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  TIPO VARCHAR2(20) NOT NULL,
  VALOR NUMBER(18,2) NOT NULL,
  SALDO_DISPONIBLE NUMBER(18,2) NOT NULL,
  ID_CUENTA NUMBER(19) NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_MOVIMIENTO_CUENTA FOREIGN KEY (ID_CUENTA)
    REFERENCES SERVICIO_CUENTAS.CUENTA(ID),
  CONSTRAINT CK_MOV_TIPO CHECK (TIPO IN ('DEPOSITO','RETIRO'))
);

CREATE INDEX SERVICIO_CUENTAS.IDX_MOVIMIENTO_CUENTA_FECHA
  ON SERVICIO_CUENTAS.MOVIMIENTO(ID_CUENTA, FECHA);

-- Secuencias
CREATE SEQUENCE SERVICIO_CUENTAS.SEQ_CUENTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SERVICIO_CUENTAS.SEQ_MOVIMIENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Clave foránea entre servicios
ALTER TABLE SERVICIO_CUENTAS.CUENTA
  ADD CONSTRAINT FK_CUENTA_CLIENTE
  FOREIGN KEY (ID_CLIENTE)
  REFERENCES SERVICIO_PERSONAS.CLIENTE (ID_CLIENTE);
 
 COMMIT;
